MONDAY_API_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjYyNTU4NTYzMCwiYWFpIjoxMSwidWlkIjoxMDAyODQ2NTIsImlhZCI6IjIwMjYtMDItMjVUMDU6NTY6NDguMDAwWiIsInBlciI6Im1lOndyaXRlIiwiYWN0aWQiOjMzOTYwNTI0LCJyZ24iOiJhcHNlMiJ9.Djy1h6sV8Twm5QgwLAP_f-fHgytYTbQFtRfskAIxVug"
WORK_ORDERS_BOARD_ID = "5026839911"
DEALS_BOARD_ID = "5026839943"